Тестовый проект вывода списка студентов
itstep-shambala/EditorForStudentsList pull request #5
Opened 2021-11-27 10:48 UTC by anst-foto

2021-11-27 10:48 UTC, anst-foto commented
![](https://github.trello.services/images/mini-trello-icon.png) [Вывод списка студентов на форму приложения](https://trello.com/c/ihp7fsqy/3-%D0%B2%D1%8B%D0%B2%D0%BE%D0%B4-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B0-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%BE%D0%B2-%D0%BD%D0%B0-%D1%84%D0%BE%D1%80%D0%BC%D1%83-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F)

2021-11-27 10:48 UTC, Presstomsk commented
Ваше письмо поступило в обработку. С Вами обязательно свяжутся.

2021-11-27 10:53 UTC, Presstomsk requested changes
Необходима конвертация `DateOfBirth`;
Нет вывода `Phones`

2021-12-18 07:34 UTC, merged

2021-12-18 07:35 UTC, Presstomsk commented
Ваше письмо поступило в обработку. С Вами обязательно свяжутся.